import { brand } from './brand.ts';

const rawUrl = process.env.NEXT_PUBLIC_SITE_URL?.trim();

/** Absolute origin with no trailing slash. Falls back to localhost in dev. */
export const siteUrl = (rawUrl && rawUrl.replace(/\/+$/, '')) || 'http://localhost:3000';

export const site = {
  url: siteUrl,
  name: brand.name,
  titleSuffix: brand.name,
  locale: 'en_US',
  lang: 'en',
  /** Static 1200x630 PNG generated by scripts/generate-brand-assets.mjs. */
  defaultOgImage: '/og/default.png',
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || undefined,
} as const;

/** Build an absolute URL from a root-relative path. */
export function absoluteUrl(path: string): string {
  if (!path.startsWith('/')) return `${siteUrl}/${path}`;
  return `${siteUrl}${path}`;
}

/**
 * Whether this build is a real public deployment that should be crawled.
 *
 * Two failure modes this closes. First, `NEXT_PUBLIC_SITE_URL` unset: the
 * fallback above is localhost, and a build shipped in that state would publish
 * a `robots.txt` pointing at `http://localhost:3000/sitemap.xml` and a sitemap
 * full of URLs no crawler can reach — which is worse than publishing nothing,
 * because it teaches the crawler the site is broken. Second, staging: a preview
 * host with the real content on it competes with production for the same
 * queries, and duplicate content is the one SEO problem that is expensive to
 * undo. `NEXT_PUBLIC_NOINDEX=true` on any non-production deploy prevents it.
 *
 * Note the limit of `robots.txt` alone: `Disallow: /` stops crawling, not
 * indexing — an externally linked URL can still appear, title-only. The nginx
 * config for any non-production host should also send `X-Robots-Tag: noindex`,
 * which is the directive that actually removes it.
 */
const LOCAL_ORIGIN = /^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])(:\d+)?$/;

export const isIndexableDeployment =
  !LOCAL_ORIGIN.test(siteUrl) && process.env.NEXT_PUBLIC_NOINDEX !== 'true';

/**
 * Central route table. Every internal link in the app goes through this so a
 * URL structure change is a one-file edit and the integrity checker can verify
 * that no route is referenced that does not exist.
 */
export const routes = {
  home: '/',
  tools: '/tools',
  tool: (slug: string) => `/tools/${slug}`,
  categories: '/categories',
  guides: '/guides',
  guide: (slug: string) => `/guides/${slug}`,
  category: (id: string) => `/categories/${id}`,
  about: '/about',
  privacy: '/privacy',
  terms: '/terms',
} as const;
